sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/dockerfile.dev -t mo29172/client ./client
script:
  - docker run -e CI=true mo29172/client npm run test

after_install:


deploy:
  provider: elasticbeanstalk
  region: "eu-west"
  app: ""
  env: ""
  bucket_name: ""
  bucket_path: ""
  on:
    branch: master
  access_key_id: 
  secret_access_key: 
