version: '3'
services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_USER: "user"
            POSTGRES_DB: 'db'
    redis:
        image: redis:latest
    api:
        build:
            context: ./server
            dockerfile: ./Dockerfile.dev
        volumes: 
            - /app/node_modules 
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGHOST=postgres
            - PGPORT=5432
            - PGUSER=user
            - PGPASSWORD=password
            - PGDATABASE=db
        ports:
            - 5000:5000
    client:
        build:
            context: ./client
            dockerfile: ./Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - 3000:3000
    worker:
        build:
            context: ./worker
            dockerfile: ./Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - 8080:80
            # 3. mutiple nginx instances